import Head from "next/head";
import Image from "next/future/image";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub } from "react-icons/ai"
import quote from "../public/quote.png"
import markdown from "../public/markdown.png"
import calculator from "../public/calculator.png"
import expenses from "../public/expenses.png"
import {useState} from "react"


export default function Home() {


  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-4">
        <section className="min-vh-100">
          <nav className="py-4 mb-5 d-flex justify-content-between">
            <h1 className="">Logo goes here</h1>
            <ul className="flex align-items-center list-group list-group-horizontal">
              <li>
                <button className="btn m-auto p-auto"><BsFillMoonStarsFill className="pointer"/></button>
              </li>
              <li>
                <a className="resume bg-primary text-white px-2 py-1 rounded-2 ms-3" href="#">Résumé</a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-3">
            <h2 className="fs-1 py-2 text-dark">Chang Bok Lee</h2>
            <h3 className="fs-4 py-2">Entry level web developer</h3>
            <p className="fs-5 py-4 text-body">Aspiring entry level web developer looking for new opportunities to learn and grow.</p>
          </div>
          <div className="fs-1 d-flex justify-content-center gap-4 text-body">
            <AiFillLinkedin />
            <AiFillGithub />
          </div>
          
          <section>
            <div>
                <h3 className="fs-4 pt-5 text-center">Projects</h3>
                <div className="d-flex flex-wrap mx-auto justify-content-center projects">
                    <div className="col-6 text-center hover_img">
                        <a href="https://random-quote-generator.changl88.repl.co/" >Random Quote Machine<span><Image src={quote}/></span></a>
                    </div>
                    <div className="col-6 text-center hover_img">
                        <a href="https://markdown-previewer.changl88.repl.co/" >Markdown Previewer<span><Image src={markdown}/></span></a>
                    </div>
                    <div className="col-6 text-center hover_img">
                        <a href="https://changl88.github.io/Frontend_Mentor_projects/calculator-app-main/" >Calculator<span><Image src={calculator}/></span></a>
                    </div>
                    <div className="col-6 text-center hover_img">
                        <a href="https://changl88.github.io/Frontend_Mentor_projects/expenses-chart-component-main/" >Expenses Chart<span><Image src={expenses}/></span></a>
                    </div>
                </div>
            </div>
          </section>
          
        </section>
      </main>
    </div>
  );
}
